name: CD
    
on:
  workflow_run:
    workflows: ["CI"]  # CI 워크플로우의 이름을 기입
    types:
      - completed
      
jobs:
  deploy:
    # build 잡이 성공한 뒤에만 실행되도록 의존성 설정
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}            # EC2 호스트 (IP 또는 도메인)
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Redis 컨테이너에서 flushall 명령 실행 (비대화형으로 실행)
            docker exec redis-app redis-cli flushall

            # 배포 스크립트 실행
            ./deploy.sh
